### ISSUE TITLE
Adding extra lines in 0.7.1

### ISSUE THREAD

**Issue by gfarrell** [NikhilKalige/docblockr#104]
Docblockr 0.7.1
Atom 0.198.0

Adding random extra lines every time I press "enter" which is quite frustrating (and clears the top line of the docblock).

**Comment by malko** [comment]
Can you please give a sample of code triggering the error + your actual docblocker settings

**Comment by saschagehlich** [comment]
Same here.

Settings: 

![screenshot 2015-05-23 15 47 30](https://cloud.githubusercontent.com/assets/119684/7784344/0b2040c6-0163-11e5-845a-f791aafb4076.png)

Happens with every file with JavaScript syntax enabled when I press enter after `/**`

**Comment by malko** [comment]
I double checked this seems resolved with latest docblockr version (0.7.3) but was reproductible with previous version.
I close this one for now re-open if you still encounter the problem after upgrading to 0.7.3 version.
