### ISSUE TITLE
working with c, not with c++ (depending on how i name the source file)

### ISSUE THREAD

**Issue by valerino** [NikhilKalige/docblockr#106]
trying a simple test.cpp:

class a {
  public:
    int myMethod (int a, int b);
};

positioning just above myMethod and typing /** just results in an empty comment block
/**
  *
  */
  int myMethod (int a, int b);

the same with a standard int main (int argc, char** argv) { }

if i rename the file as 'test.c', it works though!

**Comment by valerino** [comment]
ok, seems i found what happens, i temporarly fixed myself forcing the 
DocBlockrAtom.prototype.get_parser function to always return the c/cpp parser.

seems this:
var scope = editor.getGrammar().scopeName;
do not return the correct scope (i tried naming the file cpp, cxx, cc, nothing works ... only c).
i don't know how to mess with atom packages, can you check please ?

**Comment by malko** [comment]
resolved in #107 thanks to you
