### ISSUE TITLE
Add specs

### ISSUE THREAD

**Issue by nikhilkalige** [nikhilkalige/docblockr#108]
Add test cases

**Comment by nikhilkalige** [comment]
@malko @albertorestifo Any thoughts on this.. I have tried to add some in the develop branch

**Comment by albertorestifo** [comment]
That's an awesome approach!

This will make it super-easy to improve the parsers trough TDD. Well done! 👍 

I'll try to add some more test cases for JavaScript

**Comment by MoritzKn** [comment]
Update on the current test situation:
- *Java Script*: The JsParser has a pretty descent unit test coverage, with 73 test cases so far.
- *java*: The most important functions of the JavaParser are covert with 8 test cases.
- *rust*: All functions in the RustParser are covert with 17 test cases. Rust test cases for the Docsparser super prototype are missing completely.

**Comment by MoritzKn** [comment]
We have decent amount of specs now. I don't think this issue makes sense anymore. New changes should just come with specs so we can increase the coverage step by step
