### ISSUE TITLE
wrong parsing for one-lined functions

### ISSUE THREAD

**Issue by Rukenshia** [NikhilKalige/docblockr#112]
The parser generates a wrong documentation when parsing this:

```
function myFunc (someFunc) { someFunc(); }
```

Generated JSDoc:
```
/**
 * [myFunc description]
 * @param  {[type]} someFunc) {             someFunc( [description]
 * @return {[type]}           [description]
 */
function myFunc (someFunc) { someFunc(); }
```

**Comment by malko** [comment]
This seems more to be a problem with parentheses detection, I didn't look to the code but i think turning a regexp ungreedy should do the trick will have a look really soon.

**Comment by malko** [comment]
seems ok in develop branch will be fixed in next release @NikhilKalige can you publish a new release please ?
