### ISSUE TITLE
Is it possible to disable docblockr for //

### ISSUE THREAD

**Issue by globexdesigns** [NikhilKalige/docblockr#113]
In Javascript, I really like docblockr completing comments when I use `/**` however, it's also continuing comment blocks when I use `//` -- which I don't like. Is it possible to disable auto-comment-blocking for `//` comments? I'd like those to always be single-line.

Current behaviour:

- Type `//`
- Press Enter
- Atom will create a new line with `//`

Desired behaviour:

- Type `//`
- Press Enter
- Atom creates a blank new line

**Comment by malko** [comment]
yes just untick the "Extend double slash" options in the package settings
