### ISSUE TITLE
Too many new lines when hitting return in a comment

### ISSUE THREAD

**Issue by robballou** [NikhilKalige/docblockr#115]
Hitting return in a comment add extra line breaks. At first this seemed be a single extra line (making one return add two line breaks) but it seems to increment over time.
![dockblockr](https://cloud.githubusercontent.com/assets/46527/8659207/52f1ef64-2966-11e5-83d4-8252564ee734.gif)

This happens in multiline and single line comments. Is there a way to turn this off or fix the behavior?

**Comment by malko** [comment]
Which version of the package are you using ?
Can you please provide your package settings and what type of file are you editing when having this behavior ?

**Comment by robballou** [comment]
Yeah, here's more details:

Versions:

    docblockr: 0.7.3  
    atom: 1.0.2

Settings:

```cson
docblockr:
    align_tags: "no"
```

This happens when editing a PHP file.

**Comment by malko** [comment]
I can't reproduce here, can you please provide your full configuration, sample of code triggering the error.
It would be nice to get the list of other package you have installed.

Thanks

**Comment by robballou** [comment]
Yeah, here's my settings and packages: https://gist.github.com/robballou/d1ffc0daa72764e47a38

I haven't tried to debug locally yet, but disabling docblockr gets rid of the behavior, but probably just because that gets rid of the great return-continues-a-comment functionality :)

**Comment by malko** [comment]
thanks for info but still can't reproduce here, can you provide a sample of code triggering the error ?

**Comment by robballou** [comment]
Alright, I'm thinking this was just some sort of gremlin. I disabled pretty much everything and tried re-enabling to find if it was another culprit but couldn't find anything. :confused: I tried closing and restarting Atom yesterday and it still happened, but now it's all clear... so I'll close this.

Thank you for spending time trying to replicate!

**Comment by sparcut** [comment]
**Atom Version**: 1.12.7
**OS**: Windows 10 Home
**Settings & Packages**: https://gist.github.com/sparcut/1d39ce631731aa9d3a81a832383174dc
**Description**:  After installing the package I experienced the same problem shown in @robballou's gif expect it was adding 3 new lines instead of the 5. Between disabling my packages and restarting Atom, the problem disappeared.
