### ISSUE TITLE
Preface an example with * on every line

### ISSUE THREAD

**Issue by reggi** [nikhilkalige/docblockr#116]
Let's say I have a three line example I want to put into the doc. How do I lead each link with *?

```
function hello(c){
 return c + 1
}
```

**Comment by MoritzKn** [comment]
Sorry for the long wait! Currently Docblockr can't help you with that. But my approach would be to place the cursor at the end of the first line and the press <kbd>shift+right arrow</kbd>. Now the line break is selected an you can press <kbd>ctrl+d</kbd> until there is a cursor after every line of your example. With <kbd>Home</kbd> you can now position ever cursors a the beginnings of each line and insert the asterisk.
This may seam complicated, but if you get used to it it's pretty convenient.

In case this was still an issue, I hope this made things clear.
