### ISSUE TITLE
Return/Enter in inline comment creates two blank lines instead of one

### ISSUE THREAD

**Issue by Krinkle** [nikhilkalige/docblockr#117]
Atom: 1.0.2
atom-dockblockr: 0.7.2
1. Given the following code:

``` js
// Foo[cursor]
var a = 1;
```
1. Press Return or Enter.

Expected:

``` js
// Foo
// [cursor]
var a = 1;
```

Actual:

``` js
// Foo
// 
// [cursor]
var a = 1;
```

Disabling the atom-dockblockr plugin resolved the issue.

**Comment by benargo** [comment]
Seconded, still an issue as of 0.7.3.

**Comment by hugw** [comment]
Confirmed in 0.7.3 for me too.

**Comment by AndiDog** [comment]
It now happened to me the first time when upgrading 0.7.3 -> 0.7.4

**Comment by MoritzKn** [comment]
This could be related to #202

**Comment by MoritzKn** [comment]
Has this happened to anyone in the last time? May have been fixed by a new atom version
