### ISSUE TITLE
Perl support?

### ISSUE THREAD

**Issue by fstltna** [nikhilkalige/docblockr#119]
Any plans for perl support?

**Comment by MoritzKn** [comment]
I have no plans on implementing this and @nikhilkalige is not activity developing new functionality as well. The problem with adding new languages is that they often have many corner cases you have to think of and are therefore hard to maintain. Also I have no experiences with Perl and had to dig into the language itself first.
If some one else wants to implement this, I am happy to help and answer questions. If you're interested in doing so, I recommend looking into [#138](https://github.com/nikhilkalige/docblockr/issues/138#issuecomment-243273254). In this issue I already gave an overview on how to add a new language.
