### ISSUE TITLE
CSS Support

### ISSUE THREAD

**Issue by jiayihu** [nikhilkalige/docblockr#126]
Could you please add support for CSS based on [Idiomatic CSS](https://github.com/necolas/idiomatic-css) ?

**Comment by ethyde** [comment]
+1,

Or/and based on KSS : http://warpspire.com/kss/

Thx a lot :)

**Comment by stephjiayi** [comment]
For comments based on Idiomatic CSS I've solved with easy custom [atom snippets](https://github.com/atom/snippets).

**Comment by ethyde** [comment]
I found another workaround for idiomatic comment with : [atom-idiomatic-comments-css-snippets](https://github.com/DanielaValero/atom-idiomatic-comments-css-snippets).

It's cool, but it's not enough when i work on large project with complex styleguide, lot of css module.

And i think KSS are very close to jsDoc but for CSS :)

**Comment by MoritzKn** [comment]
What does support for CSS mean, just the basic functionality or autocomplete with code analysis too?

**Comment by jiayihu** [comment]
@MoritzKn just basic functionality but actually I solved the need easily with custom snippets and I believe it's also a better solution the adding it in docblockr
