### ISSUE TITLE
Tab inside doc block

### ISSUE THREAD

**Issue by ripples-alive** [nikhilkalige/docblockr#127]
When I press `tab` in doc block to intent, `docblockr` will sometimes insert `tab` and sometimes `white space`. However, I prefer white spaces only. Is there some settings for that I did not notice?

**Comment by zp-j** [comment]
Hello @JayvicWen, I would suggest you to use [tabs-to-spaces](https://atom.io/packages/tabs-to-spaces) when you save a file and convert tab to 2 spaces. Btw, It is suggested in the [Airbnb JavaScript Style Guide](https://github.com/airbnb/javascript#whitespace) that

> Use soft tabs set to 2 spaces

**Comment by RipplesWen** [comment]
@zp-j Thank you for the suggested package. It really works fine.
But I still think `docblockr` needs to fix this issue as almost no one would like to use both tabs and spaces in one file.
Btw, in fact, I do prefer 4 spaces as I think it's better for human reading.

**Comment by MoritzKn** [comment]
This was fixed with #190. In version 0.7.4 it shouldn't happen in anymore.
