### ISSUE TITLE
Option to disable generating "{type}"

### ISSUE THREAD

**Issue by Xample** [nikhilkalige/docblockr#134]
I am using typedoc to generate my typescript documents file. typedoc is clever enough to understand the type of a parameter and generate the right code accordingly.

For this reason I can avoid writing the parameter's type twice so instead of:

```
  /**
   * Some description
   * @param  {number} value is just a value
   * @return {[type]}       what will be returned
   */
  constructor(value: number)
```

I can dismiss the _{}_ part which gives me:

```
  /**
   * Some description
   * @param  value is just a value
   * @return       what will be returned
   */
  constructor(value: number)
```

The benefits is obviously not to have to write duplicate comment and to always generate from the code instead of metadata.

Now I have been unable to find how to setup docblockr so that it will avoid generating the {type} per default. Is there an option for this ?

**Comment by cspotcode** [comment]
Ditto; in Typescript all type information is encoded in the code itself and should be omitted from JSDoc comments.

**Comment by MoritzKn** [comment]
Thanks to #300 this is fixed now
