### ISSUE TITLE
Golang support

### ISSUE THREAD

**Issue by agaurav** [nikhilkalige/docblockr#137]
any plans for golang support?
I believe it to be very much similar to c++. I would be very much happy to help.  A brief guide or slighted documented code (for this https://github.com/nikhilkalige/docblockr/blob/master/lib/languages/cpp.js) will be very much appreciated :)

**Comment by MoritzKn** [comment]
Sorry for the loonnng delay. If you are still interested in implementing this I am happy to help answer questions. First of all I recommend looking into [#138](https://github.com/nikhilkalige/docblockr/issues/138#issuecomment-243273254). In this issue I already gave an overview on how to add a new language.

**Comment by MoritzKn** [comment]
No response, closing. Feel free to comment here again if you are still interested.

**Comment by CodyGuo** [comment]
@MoritzKn  golang support

**Comment by MoritzKn** [comment]
@CodyGuo Yeah, that is what this issue is about.. but what is your question? are you interested in adding go-lang support?
