### ISSUE TITLE
[NFR] PHPUnit support

### ISSUE THREAD

**Issue by williamokano** [nikhilkalige/docblockr#139]
Can you please add support for the following PHPUnit annotations?
- `@author`
- `@after`
- `@afterClass`
- `@backupGlobals`
- `@backupStaticAttributes`
- `@before`
- `@beforeClass`
- `@codeCoverageIgnore`
- `@covers`
- `@coversDefaultClass`
- `@coversNothing`
- `@dataProvider`
- `@depends`
- `@expectedException`
- `@expectedExceptionCode`
- `@expectedExceptionMessage`
- `@expectedExceptionMessageRegExp`
- `@group`
- `@large`
- `@medium`
- `@preserveGlobalState`
- `@requires`
- `@runTestsInSeparateProcesses`
- `@runInSeparateProcess`
- `@small`
- `@test`
- `@testdox`
- `@ticket`
- `@uses`

**Comment by gfviegas** [comment]
Docblockr is a tool to recognize your code and smartly create Doc Comments. I think it's only necessary to recognize a ``@test`` doc and ``@depends``. If you're seeking to highlights, you need to change the PHP setup of atom or add your own stylesheet,as docblockr has no styles.

Thanks!!

**Comment by williamokano** [comment]
+1

**Comment by MoritzKn** [comment]
Closing with the same reasons as #140.
