### ISSUE TITLE
Can't use Docblockr with editors in custom panes

### ISSUE THREAD

**Issue by blakeembrey** [nikhilkalige/docblockr#142]
I have a plugin which uses custom atom text editors in a preview pane, but I can't hit enter with this plugin enabled.

![image](https://cloud.githubusercontent.com/assets/1088987/11545180/aa2d2e5c-98fa-11e5-88ae-3551fbebe58a.png)

**Comment by MoritzKn** [comment]
Is this still a thing and if so what plugin do you use?

**Comment by blakeembrey** [comment]
I no longer use Atom, but it was this plugin. It occurs, IIRC, when using custom text editors in a preview pane. This happened because I built an interactive console that acted like a view (imagine the markdown viewer) and it had input fields that used Atom's text editor in mini and full-view modes. I can't remember now which it failed on, but I would think it's the full view - it was crashing when typing in a full-editor view embedded within a custom view.

**Comment by MoritzKn** [comment]
I am going to close this since I doesn't seem to be an issue for anyone else
