### ISSUE TITLE
shift+enter after the opening /** (PHP)

### ISSUE THREAD

**Issue by jorgeorpinel** [nikhilkalige/docblockr#143]
`shift+enter` after the opening `/**` is not creating a single-line comment for my var, it's just going to the next line:

```php
  /** press shift+enter
  |<- cursor moves here
  protected $plugin_dir;
  protected $plugin_url;

```

Thank you in advance!

docblockr 0.7.3
Atom 1.2.1
Mac OS X 10.10.5

**Comment by MoritzKn** [comment]
This most likely happens due to conflicts with other key bindings.
If this is still occurring, can you please use the keybinding-resolver (<kbd>cmd+.</kbd>) to figure out what exactly is execute?

**Comment by MoritzKn** [comment]
Another reason for this could be that `/**` is followed by a whitespace.
So for example:
```
/**<shift+enter>
```
works, but
```
/**  <shift+enter>
```
does not.
But this should be changed, since it works for this with multi line doc comments.

**Comment by jorgeorpinel** [comment]
This is no longer occurring.

**Comment by jorgeorpinel** [comment]
Woops I guess you meant to keep this open? I think you can reopen it so I'll leave it be. Best
