### ISSUE TITLE
spacer_between_sections setting missing text input

### ISSUE THREAD

**Issue by felixkempf** [nikhilkalige/docblockr#145]
The settings for "spacer_between_sections" only provide a checkbox, I see no possibility to set it to "after_description" so a new line is only added after the description and not between all sections.

**Comment by mattjorn** [comment]
Setting `spacer_between_sections` to `after_description` in `config.cson`doesn't seem work either. In `lib/docblockr.js`, its type is set to boolean.

**Comment by MoritzKn** [comment]
PR #145 tries to fix this.
