### ISSUE TITLE
Automate generation

### ISSUE THREAD

**Issue by mjmarianetti** [nikhilkalige/docblockr#146]
Hi,

It would be great if this package could do the following:

Select a file on the tree-view, right-click --> generate doc (or via a shortcut). And it would generate the docblocks of all the functions/methods/variables in that file.

**Comment by julmot** [comment]
There are already other plugins out there doing exactly (and only) this task. However, they seem to not work correctly...

**Comment by MoritzKn** [comment]
I don't understand why this should be useful, you would still have to go through every function and replace the placeholders. Also you probably don't want to document *every* variable and *every* function.

**Comment by MoritzKn** [comment]
No response, closing.
