### ISSUE TITLE
Package loading time

### ISSUE THREAD

**Issue by csholmq** [nikhilkalige/docblockr#147]
![image](https://cloud.githubusercontent.com/assets/1297882/11842310/2907f4ba-a403-11e5-8cdc-523026ba9c8f.png)

Takes 134 ms to load this package. How come?

**Comment by MoritzKn** [comment]
Is this still an issue in my case it is not even over 5ms?

**Comment by MoritzKn** [comment]
No response, closing. Feel free to comment here if it's still an issue.
