### ISSUE TITLE
Auto function comment are not ceated

### ISSUE THREAD

**Issue by indolentdeveloper** [nikhilkalige/docblockr#151]
in case of function defined using assignment, function comments are not generated while press of tab.

var f = function (data) {
}

I don't get comments generated for this method. I am using atom.

**Comment by dwhieb** [comment]
I'm having the same issue. v0.7.3

**Comment by phil-r** [comment]
Same here docblockr v0.7.3 atom v1.4.1

**Comment by MoritzKn** [comment]
I can't reproduce this..
Version 0.7.4 made quite a few changed to the JS function parser, so this my be solved already.
Could you please test if this is still reproducible in Version 0.8.0.

**Comment by dwhieb** [comment]
Seems to be working fine now.

**Comment by MoritzKn** [comment]
Perfect! I will close this issue for now. Feel free to reopen if it occurs again.
