### ISSUE TITLE
Short data types for PHP

### ISSUE THREAD

**Issue by umpirsky** [nikhilkalige/docblockr#153]
Scalar types should always be written in the same form. "int", not "integer"; "bool", not "boolean"; "float", not "real" or "double".

https://github.com/FriendsOfPHP/PHP-CS-Fixer

**Comment by n0o0bSina** [comment]
+1

**Comment by MoritzKn** [comment]
There already is a setting for this called 'short primitives':
If true, the primitives `boolean` and `integer` are shortened to `bool` and `int`. Default: `false`
Besides that everything should already match the requirements.

**Comment by linjialiang** [comment]
> Hope to release a new version of the revision !
> thank you !

**Comment by linjialiang** [comment]
> ok !

![default](https://user-images.githubusercontent.com/8848263/48244629-a9493100-e421-11e8-978f-6cb65df03b66.png)
