### ISSUE TITLE
Pressing tab inside a comment always adds a tab character

### ISSUE THREAD

**Issue by james-jlo-long** [nikhilkalige/docblockr#163]
When inside a comment block, pressing `tab` will always add a `\t` character even with the editor set up to indent with spaces.

To reproduce, just press `tab` within a comment.
```js
/**
 * 	test
 * 		test 2
 **/
function doSomething() {
    "use strict";
}
```

Expected:
```js
/**
 *\s\stest
 *\s\s\s\s\s\stest 2
 **/
function doSomething() {
\s\s\s\s"use strict";
}
```

Actual:
```js
/**
 *\s\ttest
 *\s\t\ttest 2
 **/
function doSomething() {
\s\s\s\s"use strict";
}
```

Is there any way to configure this?

**Comment by CubixSystem** [comment]
After update to 0.7.4 problem still exist
