### ISSUE TITLE
es6 generator function in class is not supported

### ISSUE THREAD

**Issue by julmot** [nikhilkalige/docblockr#169]
When having a generator function in a class, docblockr will not work:

``` javascript
class example{
    *example(example){
    }
}
```

The reason is that there is no `function` before `*example`.

This wasn't considered in #36. May be related to #141.

**Comment by albertorestifo** [comment]
Also objects are affected:

```js
const obj = {
  *example() { … }
}
```

**Comment by Luchanso** [comment]
+1

**Comment by MoritzKn** [comment]
This is related to #205.

**Comment by webdevian** [comment]
This looks like it can be closed now?

**Comment by MoritzKn** [comment]
Jep, thanks @webdevian for pointing it out.
