### ISSUE TITLE
JavaScript autoblock doesn't add return value

### ISSUE THREAD

**Issue by eddiemonge** [NikhilKalige/docblockr#17]
Auto adding doc block for JS doesn't seem to add a return value line

**Comment by curtisblackwell** [comment]
I'm getting the exact same results as @chriscollinsboxuk in PHP.

**Comment by jgonagle** [comment]
Ditto, in JS.

**Comment by robtarr** [comment]
The offending method is `DocsParser.prototype.get_function_return_type`: https://github.com/NikhilKalige/docblockr/blob/master/lib/docsparser.js#L202

It's trying to infer a `return` type.
```
if(name.search(/[A-Z]/) > -1)
        return null;  // no return, but should add a class
```

is the statement causing it to fail.

Anybody have any thoughts on what this method should actually be checking for?

**Comment by bryanbraun** [comment]
From the README:

> In Javascript, if the function begins with an uppercase letter then it is assumed that the function is a class definition. No @return tag is added.

`search()` returns the index of the first match, so if set our condition to only match for the 0th index then it won't trigger for caps throughout the function name. This should fix it:

```diff
- if(name.search(/[A-Z]/) > -1)
+ if(name.search(/[A-Z]/) === 0)
```

**Comment by malko** [comment]
merged for next release thx
