### ISSUE TITLE
Rustdoc support

### ISSUE THREAD

**Issue by Morosko** [nikhilkalige/docblockr#171]
I installed docblockr to use it with the rust lang. However, when I write `///` before a function and hit Enter, it just adds a new line with `///`. If I do the same just with `/**` I get this:

```
/**
 *
 */
```

`//!` doesn't work either.

In your readme you say that Rust is supported so I'm wondering if I'm doing something wrong or is it broken?

Atom Version: 1.6.0-1
docblockr version: 0.7.3
rustc version: 1.7.0

**Comment by MoritzKn** [comment]
As far as I can see it you are doing nothing wrong. Currently the package contains no implementation for parsing rust functions and automatic creating comments content.

The question is if we need something like this.
Unlike JavaScript and languages alike there is no standard way of documenting functionals (like [JsDoc](http://usejsdoc.org/) for JavaScript) for Rust, at least I couldn't find one. I think the reason for this is that Rust is statically typed language and the function signature already tells what arguments the function takes, what it returns what types the arguments have, etc..

**Comment by MoritzKn** [comment]
Forget what I said previously, I think adding a list (preferably markdown) of all param would be an enhancement.

Something like this:
```rust
//! [foo description]
//! 
//! # Params
//! - a 
//! - b 
fn foo(a: i32, b: i32) {
    
}
```

@Morosko is that what you expected?

**Comment by daboross** [comment]
@MoritzKn

I'm looking for this feature, and all I really want is to be able to press "enter" when writing a `///` or `//!` comment, and have it insert `/// ` or `//! ` on the next line. Just that would be excellent, and I don't believe anything more is really "needed" to claim Rust support.

**Comment by MoritzKn** [comment]
> my apologies

It's fine, don't worry.
> I have not used this project and thus do not know if this is an implemented feature yet.

This indeed already works.

> In general, the convention for rust comments is to just make the human readable, and not provide specific doc bits for any of the different parameters for functions.

This is what I've seen so far too, but maybe it would be cool anyway.. I don't know. But because of that this has no priory for me. Hover if we implement this, maybe we can orientate it on [atomdoc](https://github.com/atom/atomdoc) which is also markdown bases and not so strict.

**Comment by MoritzKn** [comment]
Closing since the core functionality is already implemented.

**Comment by jwir3** [comment]
Sorry to hit up an old thread, but I don't believe this is currently working. I am using:
```
apm  2.1.7
npm  6.2.0
node 8.9.3 x64
atom 1.38.2
```

and docblockr version: `0.13.7`, but, when in a `.rs` file, if I type:
```
///
```

and hit return, it doesn't continue the comment block on the next line. (This is also the case with `//!`).
