### ISSUE TITLE
Haskell support

### ISSUE THREAD

**Issue by wdanilo** [nikhilkalige/docblockr#173]
Hello! Would it be possible to add Haskell's haddoc support (https://www.haskell.org/haddock/doc/html/markup.html) ?

**Comment by MoritzKn** [comment]
I have no plans on implementing this and @nikhilkalige is not activity developing new functionality as well. The problem with adding new languages is that they often have many corner cases you have to think of and are therefore hard to maintain. Also I have no experiences with Haskell and had to dig into the language itself first.
If some one else wants to implement this, I am happy to help and answer questions. If you're interested in doing so, I recommend looking into [#138](https://github.com/nikhilkalige/docblockr/issues/138#issuecomment-243273254). In this issue I already gave an overview on how to add a new language.
Also there are more requested languages.
