### ISSUE TITLE
Add a dependency system and plug the existing deps into it

### ISSUE THREAD

**Issue by rbecheras** [nikhilkalige/docblockr#178]
The aim is to prevent the iss #14 and eventual future issues of the same kind if the plugin grow-up with other atom plugin dependencies.

**Comment by rbecheras** [comment]
Here is a npm package built for this purpose: https://github.com/travs/atom-package-dependencies
I'll submit a PR in some minutes including this new feature.

**Comment by rbecheras** [comment]
Here is my fork: https://github.com/rbecheras/docblockr

**Comment by rbecheras** [comment]
I upgraded the `develop` branch from master (the last version bump) and I created a new topic branch from `develop`: https://github.com/rbecheras/docblockr/tree/iss-%2374-feature-plugin-dependencies

**Comment by nikhilkalige** [comment]
Fixed with 749f59e1cb249d8c47e6dd49c29419ce0c522b4e
