### ISSUE TITLE
comment extension

### ISSUE THREAD

**Issue by andy9775** [nikhilkalige/docblockr#193]
Is there a way to disable comment extension for single line comments (`//`)? I think that it makes sense to do comment extension inside comment blocks (`/* comment */` or `/** comment */`) but not on single line (double slash) comments. The reason being that single line comments should be just that - a single line.

**Comment by MoritzKn** [comment]
There is a option for this: You can go to `Preferences > Packages > Docblockr > Settings` and disable `Extend double slash`. :smile:

**Comment by andy9775** [comment]
Ooops. Thanks @MoritzKn didn't notice it, sorry!
