### ISSUE TITLE
Issues with extra tags and changelog

### ISSUE THREAD

**Issue by tocaibiza** [NikhilKalige/docblockr#20]
Hey there,

Quick question: how should we fill the extra tags in settings field? I have no luck setting them yet. Is it array, comma separated, something else?

Regarding changelog - recent changes are pointed to August, while we are July yet. :)

P.S. Something else I just came to - Atom does not pick docblockr for update, when there is new version here. I was stuck to 0.5.2 for a while, until I saw 0.5.6 here. Same issue with 0.5.7 - it doesn't load as "update", but if I reinstall it, the recent version will be applied.

Thanks!

**Comment by curtisblackwell** [comment]
I have `@author Curtis Blackwell` in my Extra Tags field, but it's not working. I tried restarting Atom, but it still didn't work.

**Comment by ernestoalejo** [comment]
I had problems too disabling "Align tags" until I applied #58

**Comment by DonkeyAfterDark** [comment]
Same issue as Curtis. No idea how the Extra Tags field should work.

I've tried:

@author Me
[@author Me]
['@author Me']

Nothing new appears when I type /** and press enter. Just the normal stuff, @type, @return.

**Comment by curtisblackwell** [comment]
Mine actually does work with PHP now, but not JavaScript. v0.11.0 for posterity.

**Comment by MoritzKn** [comment]
@DonkeyAfterDark @curtisblackwell The "Extra tags" setting should be an array of strings. If your config looks like this it should insert the string `@foo bar`:
```coffee
'*'
  docblockr:
    deep_indent: true
    extra_tags: [
      '@foo bar'
    ]
```

**Comment by curtisblackwell** [comment]
I just used the UI and set the single one. `@author Curtis Blackwell`. Not a big enough worry for me to go diving into CSON.

**Comment by MoritzKn** [comment]
Understandable, unfortunately the UI can't represent array type settings correctly.
