### ISSUE TITLE
PHP Param type bool isn't recognized when default value is set

### ISSUE THREAD

**Issue by rzelnik** [nikhilkalige/docblockr#200]
When I create a function with boolean parameter, it is recognized by Docblockr.

```php
/**
 * [foo description]
 * @param  bool   $bar [description]
 * @return [type]      [description]
 */
public function foo(bool $bar) {
    return TRUE;
}
```

When I put a default value, Docblockr is unable to recognize it.
```php
/**
 * [foo description]
 * @param  [type] $bar [description] <------------- see [type]
 * @return [type]      [description]
 */
public function foo(bool $bar = TRUE) {
    return TRUE;
}
```

**Comment by MoritzKn** [comment]
Currently only lowercase `true` and `false` is recognized as boolean. This has to be fixed in the PHP parser.

**Comment by MoritzKn** [comment]
Thanks for reporting this!
I fixed this with commit [9c4486](https://github.com/nikhilkalige/docblockr/commit/9c4486bcdaddb4f114061c8a55ac5837eb44e47c).
In version 0.8.2 this should work.

**Comment by rzelnik** [comment]
Thank you for quick fix. It is working well now.
