### ISSUE TITLE
Can't Use It On Bracktes 

### ISSUE THREAD

**Issue by asfgasdfa** [nikhilkalige/docblockr#206]
Please port it for bracktes i want to use it on bracktes please port it for bracktes please.

**Comment by MoritzKn** [comment]
Unfavorable it don't seems that easy. Brackets and Atom doesn't share the same code base. Brackets is an entirely different editor, both of them use web technology (JS, HTML, CSS) but have different APIs. So I don't see Docblockr being ported to Brackets, but I found this Brackets package which seems to be similar to Docblockr: [brackets-FuncDocr](https://github.com/Wikunia/brackets-FuncDocr).
