### ISSUE TITLE
Add Support for AtomDoc

### ISSUE THREAD

**Issue by GarthDB** [nikhilkalige/docblockr#216]
[AtomDoc](https://github.com/atom/atomdoc) is a different style of documentation than JSDoc - a bit simpler and based on Markdown.

I love using docblockr, but it would be much more helpful to have atomdoc style stubs. I am going to fork this repo and play with it, but I'm not sure if it should be a separate package or an option in this package.

**Comment by MoritzKn** [comment]
I saw you already forked this repo and did some changes, but I think this could easily be implemented by adding an option for this and interchanging the `format_function` and `format_var` methods. Probably the best way would be to add a mechanism for using alternative formatting methods.

Please let me know if you are interested in doing something like this or if you prefer implementing this as a separate package.

**Comment by GarthDB** [comment]
@MoritzKn it's a deeper change than I expected - some of it deals with the fact that AtomDoc doesn't use the `@` notation anywhere and the dockblockr and jsdoc use it for identifying things.

For now, I think a fork is fine, I have a lot of clean-up to do in the package and by the time I get it the way I like, it may not resemble this package much.
