### ISSUE TITLE
Why dependency on the core "snippets" package?

### ISSUE THREAD

**Issue by sompylasar** [nikhilkalige/docblockr#217]
I've just got the "Please enable Snippets package for Docblockr to function properly" exception because I've disabled the snippets – they come into way in the autocomplete list, for example, when I autocomplete "error" it gives me "console.error()" which is totally not what I needed, very frustrating.

So, what's cool about them that cannot be implemented with the core editor API?

**Comment by sompylasar** [comment]
Found out that "autocomplete-snippets" is a separate package, and it is the one that gets in the way and frustrates me, so re-enabled the "snippets" package.

**Comment by MoritzKn** [comment]
As far a I understand this the snippets package is used for the auto completion and provides the tab functionality.

This:
 ![](https://raw.githubusercontent.com/NikhilKalige/docblockr/master/resources/type-hinting.gif).

**Comment by sompylasar** [comment]
@MoritzKn Got it, thanks!
