### ISSUE TITLE
v0.8.1 Parse-enter fails when there's a url in the line

### ISSUE THREAD

**Issue by emileber** [nikhilkalige/docblockr#218]
Since v0.8.1 (including all updates after), If I have a comment like the following, containing a url inside, triggering the `docblockr:parse-enter` command at the end of the line does nothing.

```javascript
/**
 * test http://test.com/ other text whatever "parse-enter doesn't work HERE"
 */
```

It works as expected in v0.8.0 and also works if there's no url inside the comment line.

**Comment by MoritzKn** [comment]
Fixed in v0.8.5
