### ISSUE TITLE
[Feature Suggestion] Output Documentation as HTML

### ISSUE THREAD

**Issue by markediez** [nikhilkalige/docblockr#221]
Love this plugin, wish it could output an html file for me like doxygen with all the documentation of my code.

**Comment by MoritzKn** [comment]
This is beyond the scope of this plugin. Docblockr is designed to make *writing* documentation easier, not to generate a the HTML page with the documentation. For this purpose various better tools already exist. Also technically the task off generating a HTML page is a completely new thing that would share none off the already existing code.
