### ISSUE TITLE
The enter key appears to be pressed twice

### ISSUE THREAD

**Issue by sbrl** [nikhilkalige/docblockr#224]
If I type `/**` and then hit enter, it now not only creates the documentation block, but adds a new line in the place of _`[thing desciption]`_ bit. It has just started happening now after this last update. It did not do this in the previous update.

**OS:** Windows 10
**Atom version:** 1.10.2
**Docblockr version:** 0.8.7

**Comment by MoritzKn** [comment]
This is a duplicate of #224. People seem to randomly experience this after updating the package. See the other issue for possible workarounds.

**Comment by sbrl** [comment]
This issueis a duplicate of itself, @MoritzKn? Wat?

**Comment by MoritzKn** [comment]
Ohh sorry, I meant #202.

**Comment by sbrl** [comment]
Ah, cool. Thanks!
