### ISSUE TITLE
Template

### ISSUE THREAD

**Issue by gubi** [nikhilkalige/docblockr#226]
Please, add the possibility to create a custom comment template

**Comment by MoritzKn** [comment]
Somewhat related to #31. 
What exactly do you mean by "custom comment template"?
There are already a few options to control the style of the generated comments, maybe one of those does what you want. Take a look at the [config section](https://github.com/nikhilkalige/docblockr#configuration).

**Comment by MoritzKn** [comment]
No response, closing.
