### ISSUE TITLE
Please replace `@return` with `@returns`

### ISSUE THREAD

**Issue by horosgrisa** [nikhilkalige/docblockr#230]
http://usejsdoc.org/tags-returns.html
Now I use eslint plugin for jsdoc, and obtain error:`Invalid JSDoc tag (preference). Replace "return" JSDoc tag with "returns"`

**Comment by MoritzKn** [comment]
As described at the linked jsDoc tag reference page both (`@return` and `@returns`) are valid and synonyms. But if you prefer `@returns`, you can change this with the `return_tag` setting.
> **`return_tag` (String)** The text which should be used for a `@return` tag. By default, `@return` is used, however this can be changed to `@returns` if you use that style.

See: https://github.com/nikhilkalige/docblockr/blob/master/README.md#configuration
