### ISSUE TITLE
Body of method comment is not autogenerated if return type is template (C++)

### ISSUE THREAD

**Issue by ricardojuanpalmaduran** [nikhilkalige/docblockr#234]
In C++, if you type /** at the beginning of a method and then hit enter, the body of the comment section is autogenereated, including parameter names and return statement.

If the return type of the function is templated (for instance, std::vector<int>), however, no body is autogenerated.

**Comment by MoritzKn** [comment]
I can reproduce that. This code won't generate annotations.
```cpp
vector<int> foo() {
}
```

**Comment by MoritzKn** [comment]
This is probably pretty easy to fix. It looks like only  `CppParser.prototype.parse_function` has to be changed. If someone is interested in adressing this, take a look at: [languages/cpp.js L29](https://github.com/nikhilkalige/docblockr/blob/master/lib/languages/cpp.js#L29)

**Comment by MoritzKn** [comment]
Fix in #272 by @audreyseo and shipped with `v0.10.5`
