### ISSUE TITLE
Support Processing documenting?

### ISSUE THREAD

**Issue by eadwu** [nikhilkalige/docblockr#235]
From what I know it has a similar syntax to Java.

**Comment by Kutoru** [comment]
Uh like extending the languages that the package can document.

**Comment by MoritzKn** [comment]
Oh, now I get it. I wasn't aware that possessing is a programming language.
I don't plan to add new languages and @nikhilkalige isn't activity developing new functionality either (as far as I'm aware). 
The problem with adding new languages is that they often have many corner cases you have to think of and are therefore hard to maintain. Also I have no experiences with Processing and had to dig into the language itself first. And also there are more requested languages.
But if you would like to implement this, I would be happy to help and answer your questions. If you're interested in doing so, I recommend looking into #138. In this issue I already gave an overview on how to add support for a new language.

**Comment by BellemareMederic** [comment]
like java it will be nice have a documentation generator to export in basic HTML page like javadoc

http://www.oracle.com/technetwork/java/javase/documentation/index-jsp-135444.html

**Comment by audreyseo** [comment]
Processing is based off of Java; they're basically the same thing (Processing was written in Java, Processing libraries are written in Java, I never formally learned Java, just Processing).

@MoritzKn I'd be happy to create a Processing parser, but you can use all of the features that you can use in Java in Processing, and there are only a few very small differences, so if we could make the package see Processing files as Java files, we could use that as a starting point, and work on a parser later, if we really need to. I'm not very familiar with how Atom packages work though, or even sure if this is a possibility.

**Comment by MoritzKn** [comment]
As suggested by @audreyseo I quickly hacked together support for processing by extending the java parser: #275. Please test out the `add-support-processing` branch and let me now what you think by commenting in the corresponding PR.

**Comment by MoritzKn** [comment]
Support for Processing landed in `v0.11`
