### ISSUE TITLE
TextEditor.get is deprecated

### ISSUE THREAD

**Issue by nunocastromartins** [nikhilkalige/docblockr#238]
From the Deprecation Cop in `Atom 1.13.0` (issue appears when calling `Docblockr: Decorate`):

`TextEditor.prototype.displayBuffer` has always been private, but now it is gone. Reading the `displayBuffer` property now returns a reference to the containing `TextEditor`, which now provides *some* of the API of the defunct `DisplayBuffer` class.
```
TextEditor.get (/usr/lib/atom/src/text-editor.js:101:14)
DocBlockrAtom.scope_range (/home/nunomartins/.atom/packages/docblockr/lib/docblockr-worker.js:830:24)
DocBlockrAtom.decorate_command (/home/nunomartins/.atom/packages/docblockr/lib/docblockr-worker.js:411:30)
atom-workspace.<anonymous> (/home/nunomartins/.atom/packages/docblockr/lib/docblockr-worker.js:162:16)
CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:259:29)
<unknown> (/usr/lib/atom/src/command-registry.js:3:59)
```

**Comment by MoritzKn** [comment]
Thanks for reporting!
Fixed with 84e2c62, will be available with the next release.
