### ISSUE TITLE
@param tag should be followed with name of parameter

### ISSUE THREAD

**Issue by bclinthall** [nikhilkalige/docblockr#242]
Where javadoc specifications need to be followed, @param tags should be followed with the name of the parameter, not the data type. http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html#@param

**Comment by kathiedart** [comment]
Would an option be available to change to this option everywhere?

**Comment by kingcody** [comment]
@bclinthall @danwdart version `0.13.5` includes this: https://github.com/nikhilkalige/docblockr/blob/master/lib/docsparser.js#L159-L170

Given that the `typeInfo` setting for java is `false` this issue should be resolved. If either of you can test and confirm, that would be great.

**Comment by MoritzKn** [comment]
Fixed by 0a18ecdf and released with `v0.13.7`

**Comment by danwdart** [comment]
I think it was PHP that concerned me about this one - I'll see if this is an option - although it could also be that my text editor plugin needs an update to get in line with docblockr.
