### ISSUE TITLE
**/ for comment closer?

### ISSUE THREAD

**Issue by kathiedart** [nikhilkalige/docblockr#254]
I thought some of the standards (especially for PHP) were that the comment closer was **/
Sounds petty, but might fail some particularly nitty tests.
Does anyone know if the standards had changed?

**Comment by MoritzKn** [comment]
I've never seen that and I don't think it's standard..
See 
- http://www.phpdoc.de/doc/doccomments.html
- https://www.phpdoc.org/docs/latest/getting-started/your-first-set-of-documentation.html#what-does-a-docblock-look-like

Feel free to comment here if you have other information.

**Comment by kathiedart** [comment]
Hmm, fair enough, must've been my OCD manager
