### ISSUE TITLE
Feature request: Generate docblocks on all properties/methods in a file

### ISSUE THREAD

**Issue by lxg** [nikhilkalige/docblockr#256]
During refactoring, it would be helpful to generate *all* docblocks on all properties/methods of a file (which do not already have one). A more sophisticated implementation would even be able to complete or update existing docblocks. This feature could be accessible through the “Packages” menu or a key stroke.

**Comment by DonkeyAfterDark** [comment]
Ohhhh, that would be cool.

**Comment by MoritzKn** [comment]
I don't understand why this should be useful, you would still have to go through every function and replace the placeholders. Also you probably don't want to document *every* variable and *every* function.

This was already mentioned in #146

**Comment by lxg** [comment]
I realize that this is a duplicate of #146.

Why should this be useful? Because it would spare me the tedious work of manually adding the docblock itself. Also, the tool could read most of the properties from a method’s signature, so that would speed up things, too.

**Comment by MoritzKn** [comment]
Yeah, but the automated docblock itself doesn't have any value. The value comes from filling out the placeholders. And to do this you have to go through the file anyway. I still don't see how this is useful. It would also be complex to implement.
