### ISSUE TITLE
a bug that repeat single line comment with cjk-char when start  a new line

### ISSUE THREAD

**Issue by netmou** [nikhilkalige/docblockr#258]
write a comment like ‘//这是一行注释 ’ in a php file  with cjk-char ,then start a new line at the end, the comment will become like follow:
//这是一行注释
//这是一行注释

**Comment by netmou** [comment]
env like follow:
atom v16.0
docblockr 0.9.4

**Comment by MoritzKn** [comment]
Duplicate of #307
