### ISSUE TITLE
Golang support?

### ISSUE THREAD

**Issue by gerardo8a** [nikhilkalige/docblockr#263]
Planning to build golang support ? 🙏

**Comment by MoritzKn** [comment]
I have no plans to add Golang support and @nikhilkalige is not activity developing new functionality as well. The problem with adding new languages is that they often have many corner cases you have to think of and are therefore hard to maintain. Also I have no experiences with Golang and had to dig into the language itself first.
If some one else wants to implement this, I am happy to help and answer questions. If you're interested in doing so, I recommend looking into #138. In this issue I already gave an overview on how to add a new language. 
Adding Golang support was also discussed in #137.
