### ISSUE TITLE
Highlighting woes

### ISSUE THREAD

**Issue by jhabdas** [nikhilkalige/docblockr#270]
This behavior can be seen in the examples in the `README`. Is there a workaround for getting syntax highlighting to work for things like `@param` with DocBlockr?

This seems like one of the most important features, yet I constantly find myself looking grey walls of text like this, even when initializing the block using DocBlockr:

<img width="807" alt="screen shot 2017-06-05 at 4 36 07 pm" src="https://cloud.githubusercontent.com/assets/440298/26776759/217b6216-4a0d-11e7-8100-9f1502a9fba0.png">

Atom 1.16.0 x64 + DocBlockr 0.10.3

I have a short list of 22 community packages installed. If it would be valuable to dump them here I'm happy to do so. Meanwhile I'm upgrading to Atom 1.17.0 to see if the issue persists.

**Comment by jhabdas** [comment]
Looks like upgrading to 1.17.x did the trick! 🌮 

<img width="823" alt="screen shot 2017-06-05 at 5 23 26 pm" src="https://cloud.githubusercontent.com/assets/440298/26778441/cdf61468-4a13-11e7-87ef-f4583c5b1968.png">

**Comment by jhabdas** [comment]
WRT `@exception` not being highlighted, I simply changed to `@throws`. And for the return value I updated to `{Promise<Object>[]}` which feels more correct. 🍕 🍕

**Comment by MoritzKn** [comment]
The highlighting in doc commends is not defined by docblockr, but by the individual language packages.
In your case this would be [atom/language-javascript](https://github.com/atom/language-javascript).
Perhaps open an issue for your `@exception` vs `@throws` problem there.

**Comment by jhabdas** [comment]
No shit? Fooled me. Thanks for the info.
