### ISSUE TITLE
Doesn't play nice with other extensions that add newline keybindings

### ISSUE THREAD

**Issue by markasoftware** [nikhilkalige/docblockr#271]
I'm mainly referring to things like vim-mode and vim-mode-plus. When using the `o` keybinding to create a new line, it doesn't trigger docblockr's newline thing to add a *.

**Comment by MoritzKn** [comment]
Docblockr uses the command `docblockr:parse-enter` to do all the magic. If there is nothing to do it hands over to the next key binding. So you could try binding `docblockr:parse-enter` to <kbd>o</kbd>.  But don't expect that to work with thinks like "insert a new line above the cursor"; it is hard coded where the new line is inserted.

**Comment by MoritzKn** [comment]
I assume that helped. Feel free to comment here if it's still an issue.
