### ISSUE TITLE
Doc for final methods in PHP doesn't work

### ISSUE THREAD

**Issue by sharifzadesina** [nikhilkalige/docblockr#276]
See the GIF:
![screencast from 06-26-2017 06-36-18 pm](https://user-images.githubusercontent.com/15300551/27543098-6908c0f0-5a9e-11e7-8174-6c8f09817a08.gif)

**Comment by MoritzKn** [comment]
This was implemented by @jeremyvii in #277 and shipped with `v0.10.6`
