### ISSUE TITLE
cant auto complete **/

### ISSUE THREAD

**Issue by buzai** [nikhilkalige/docblockr#279]
when i input '/**' and press tab or enter
it only add a new line '*'

eg:
input 
/**
then press tab
/**
*

**Comment by MoritzKn** [comment]
Thanks for reporting! Unfortunate I am unable to reproduce this. In what language dose this issue occur?

**Comment by buzai** [comment]
@MoritzKn thanck u reply me 
I use nodejs, and es6.
system is ubuntu16 , atom 1.18.0.

now i think it is es6 yeild cause this problem.

```
    /**
    // 删除文章
    * deleteArticle(data) {
```
when function has a * , it let atom cant complete.

**Comment by MoritzKn** [comment]
Yes this seams to be a problem with generator functions defined using the class shorthand syntax:
```js
class Foo {
  thisWorks: function*() { }

  *thisDoesNotWork() {}
}
```

**Comment by buzai** [comment]
@MoritzKn  thank u

**Comment by buzai** [comment]
@MoritzKn this bug is fixed or not?

**Comment by MoritzKn** [comment]
Thanks to #292 this should be fixed now.
