### ISSUE TITLE
Issue with new array syntax - PHP line 82

### ISSUE THREAD

**Issue by crot4lus** [nikhilkalige/docblockr#280]
When typing /** and hitting enter if the function below has an array using square bracket syntax, it throws up the error:

Cannot read property '1' of null - lib/languages/php.js line 82

`function($param_1, $param_2 = ['1','2','3'])`

This isn't a problem as long as you use the original array syntax.

`function($param_1, $param_2 = array('1','2','3'))`

Thanks for the good work on the plugin, hopefully this will help resolve this issue.

**Comment by MoritzKn** [comment]
Fixed by @jeremyvii in #298 and released with `v0.13.3`
