### ISSUE TITLE
Support for VSCode

### ISSUE THREAD

**Issue by york-xtrem** [nikhilkalige/docblockr#283]
This package seems exceptional! Have you thought to move it to VSCode?

Thank you

**Comment by javisperez** [comment]
+1 ! Do you have any plan on migrating this to VSCode? I really love this package

**Comment by MoritzKn** [comment]
No, as far as I know there are no plans on porting this to VSCode. Also it's not trivial to port some Atom package to VSCode. Probably it would even be easier to write a new plugin from scratch. However I assume there is already a similar plugin for VSCode anyway.
