### ISSUE TITLE
Feature Request: Support for Go language

### ISSUE THREAD

**Issue by lstep** [nikhilkalige/docblockr#289]

**Comment by MoritzKn** [comment]
I have no plans on implementing this. The problem with adding new languages is that they often have many corner cases you have to think of and are therefore hard to maintain. Also I have no experiences with Go and had to dig into the language itself first.
If someone else wants to implement this, I am happy to help and answer questions. If you're interested in doing so, I recommend looking into #138. In this issue I already gave a rough overview on how to add a new language.
