### ISSUE TITLE
javascript docblock for class variable notation

### ISSUE THREAD

**Issue by alexwenzel** [NikhilKalige/docblockr#29]
I am getting this error when I try to docblock a class property in javascript:

````
Uncaught TypeError: Cannot read property 'replace' of undefined c:\Users\****\.atom\packages\docblockr\lib\docsparser.js:7
````

Example of what I try to docblock (I trigger this with ``/**``):

````
this.options = {
    swfPath: '',
    supplied: 'mp3',
    wmode: "window",
};
````

I am working with Atom on a Windows 7 maschine.

**Comment by malko** [comment]
Can't reproduce with latest docblocker version. I imagine previous upgrades solved this problem, i close the issue for now but feel free to re-open if you experience it again.
