### ISSUE TITLE
Feature request: automatic @class @method @memberof etc

### ISSUE THREAD

**Issue by giorgiobeggiora** [nikhilkalige/docblockr#295]
Hi, i use this really useful package for JavaScript, and i tihnk that it will be cool that when i create a documentation block the @class, @method, @memberof and similar tags will be automatically added with the correct names. Is it possible to add this as an option? Thanks :)

**Comment by MoritzKn** [comment]
The `@class`, `@method`, and `@memberof` annotations aren't needed in cases were it's obvious. For example if you have a class like this:
```
/**
 * Class for Foo
 */
class Foo {
  bar() {}
}
```
this is just fine. No `@class`, `@method`, or `@memberof` needed here. Therefore it doesn't make sense to auto generate those annotations.

**Comment by giorgiobeggiora** [comment]
one reason to use those tags is that templates like [docdash](https://github.com/clenemt/docdash) use them for their grouping feature (in the left panel menu)

**Comment by MoritzKn** [comment]
Could you please give a code example where you would expect auto generation of those annotations?

**Comment by giorgiobeggiora** [comment]
code example: 
```
/**
 * my product class
 * @class Product
 */
class Product () {
  /**
   * my 1st method
   * @method method1
   * @memberof Product
   */
  method1 () {}
  /**
   * my 2nd method
   * @method method2
   * @memberof Product
   */
  method2 () {}
}

// other tags like @module @function ...

```
result (docdash left bar):

**CLASSES**
Product
| method1
| method2

**MODULES**
...
...

**FUNCTIONS**
...
...

Thank you.

**Comment by MoritzKn** [comment]
Because you are using the class syntax jsdoc, is able to automatically understand that `Product` is a class (no `@class` needed here), `method1` and `method2` are methods (no `@method` needed) and that `method1` and `method2` are members of `Product` (no `@memberof` needed here).
I just tried it out with your example.

**Comment by giorgiobeggiora** [comment]
I created a small example project, you can find it here:

https://drive.google.com/open?id=19sG9vos1gylTh0fGGY5uTXrCz1RjtO-b

I prepared some npm scripts to show you what i mean:
- **jsdoc**: creates documentation using [jsdoc](https://www.npmjs.com/package/jsdoc) and default template.
Fails: no. Autodetect: no. Grouping: no.
- **jsdoc-docdash**: creates default documentation using [jsdoc](https://www.npmjs.com/package/jsdoc) and [docdash](https://github.com/clenemt/docdash) template.
Fails: no. Autodetect: no. Grouping: Yes.
- **documentation**: creates documentation using [documentation](https://www.npmjs.com/package/documentation) and default template.
Fails: no. Autodetect: yes. Grouping: no.
- **documentation-docdash**: creates default documentation using [documentation](https://www.npmjs.com/package/documentation) and [docdash](https://github.com/clenemt/docdash) template.
Fails: Yes.

**Comment by MoritzKn** [comment]
The problem here seem to be that JSDoc does not follow imports or something. Even with the annotations no the class does not appear in the menu.

As I stayed before, you don't need to annotate ES 2015 classes:
>  SDoc 3 makes it easy to document classes that follow the ECMAScript 2015 specification. You don't need to use tags such as `@class` and `@constructor` with ES 2015 classes—JSDoc automatically identifies classes and their constructors simply by parsing your code. ES 2015 classes are supported in JSDoc 3.4.0 and later.

-- http://usejsdoc.org/howto-es2015-classes.html

Maybe earlier you used a version older then 3.4.0?

**Comment by giorgiobeggiora** [comment]
my fault, there was an issue in the scripts declared in package.json, now they follow imports.
I uploaded again the zip (the link remains the same) and added another module with jsdoc tags, so you can see the difference. For the one without tags there is no automatic identification.

**Comment by giorgiobeggiora** [comment]
did you check the latest zip? thanks.

**Comment by MoritzKn** [comment]
I did now eventually and it doesn't seem to work:

```
~/Downloads/testdoc> npm run jsdoc

> @ jsdoc /home/moritz/Downloads/testdoc
> jsdoc src -r -d doc --verbose

Parsing /home/moritz/Downloads/testdoc/src/testdoc.js ...
Parsing /home/moritz/Downloads/testdoc/src/testdocmodule.js ...
ERROR: Unable to parse a tag's type expression for source file /home/moritz/Downloads/testdoc/src/testdocmodule.js in line 6 with tag title "return" and text "{[type]} [description]": Invalid type expression "[type]": Expected "!", "$", "'", "(", "*", ".", "...", "0", "?", "@", "Function", "\"", "\\", "_", "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do", "else", "enum", "export", "extends", "false", "finally", "for", "function", "if", "implements", "import", "in", "instanceof", "interface", "let", "new", "null", "package", "private", "protected", "public", "return", "static", "super", "switch", "this", "throw", "true", "try", "typeof", "undefined", "var", "void", "while", "with", "yield", "{", Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode titlecase letter, Unicode uppercase letter or [1-9] but "[" found.
....
```

**Comment by giorgiobeggiora** [comment]
just replace `{[type]}` with `{object}` in `testdocmodule.js` and `testdocmodulewithtags.js`

**Comment by giorgiobeggiora** [comment]
Did you test it? Thanks.
