### ISSUE TITLE
Javascript boolean primitive doesn't lowercase

### ISSUE THREAD

**Issue by DustinJSilk** [nikhilkalige/docblockr#299]
Setting primitives to lowercase doesn't work with booleans.

https://github.com/nikhilkalige/docblockr/blob/8dafc46ba98f445620dc753886c980c3ddee39b8/lib/languages/javascript.js#L232

**Comment by MoritzKn** [comment]
Yeah, that oviously a wrong. Good catch. Fixed with `0.13.4`

**Comment by DustinJSilk** [comment]
Brilliant thanks. Keep up the good work!
