### ISSUE TITLE
Auto comment does not match Javadoc format

### ISSUE THREAD

**Issue by WilliamYuhangLee** [nikhilkalige/docblockr#305]
According to the [official Javadoc Documentation](http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html#@param), a @param label is supposed to be followed by the variable's name, not its type. In addition, the documentation recommends the first phrase of the description (for a @param label) to be the type of the variable.
For example:
`@param name a String that represents a name`
where "name" is the variable's name and "a String" is the type phrase.
Could you please adjust the auto comment for java to match the specified format?

**Comment by MoritzKn** [comment]
This is a duplicate of #242. However I fixed it with `v0.13.7` anyway.
