### ISSUE TITLE
a bug in php file width Chinese char

### ISSUE THREAD

**Issue by netmou** [nikhilkalige/docblockr#307]
![2018-02-26_08-25-28](https://user-images.githubusercontent.com/7068058/36648467-e8c20eaa-1ace-11e8-8dfc-d374e13288a8.gif)

**Comment by MoritzKn** [comment]
What character is this in beginning of the 3rd line? Docblockr repeats all white space characters at the beginning of the line. I don't quite see the problem yet. I don't understand Chinese though.

**Comment by netmou** [comment]
just a normal space

**Comment by MoritzKn** [comment]
This is actually wanted behavior and I don't think it has to do with the Chinese characters. It ensures comments like this work:
```
/*
 * The first line is indented by one space
 * The second line should be too
 * @param foo A comment for some param...
 *            ... that could span multiple lines
 */
```
