### ISSUE TITLE
Single line PHPDoc @var comment

### ISSUE THREAD

**Issue by matthewspencer** [nikhilkalige/docblockr#311]
In the Sublime Text package it is possible to create either single or multi line [`@var`](http://docs.phpdoc.org/references/phpdoc/tags/var.html) comments for class variables using the following keybindings:

`/**`<kbd>spacebar</kbd> turns into:
```/** @var [type] [description] */```

`/**`<kbd>tab</kbd> turns into:
```
/**
 * [description]
 * @var [type]
 */
```

Is there a way to add a keybinding for the single line comment in the Atom package?

**Comment by MoritzKn** [comment]
Sorry for the late reply. There is: `docblockr:parse-inline` the default binding should be <kbd>shift</kbd>+<kbd>enter</kbd>

**Comment by matthewspencer** [comment]
Ah! Thank you! I see it gets overwritten in my editor by another command. I’ll remap. 👍
