### ISSUE TITLE
autocomplete-plus interrupts performance of docblockr

### ISSUE THREAD

**Issue by intafon** [nikhilkalige/docblockr#314]
When utilizing docblockr to generate jsdoc comments, typing a period at the end of the description field (or any other for that matter) and hitting tab selects the popped up suggestion from autocomplete-plus. This totally screws up the usage of docblockr.

I wasn't sure if there is a proper "fix" for this, but the work-around is to add ".comment" in the "Scope Blacklist" field in the autocomplete-plus package settings. This seems to get docblockr working its awesome magic again.

If you want, I can add a note to the Readme -- I think that is the easiest "fix" for this at the moment.

**Comment by MoritzKn** [comment]
I don't think there is a proper fix for this. I wouldn't even call it a bug – just two packages responding to the same key: snippets and autocomplete-plus. Two tips however:
- You can also bind `autocomplete-plus:confirm` to another key. I believe you could also do this only for the comment scope
- Press <kbd>esc</kbd> before pressing <kbd>tab</kbd> in case the autocomplete menu is open
