### ISSUE TITLE
Alignment of block comment end

### ISSUE THREAD

**Issue by matthias-ccri** [nikhilkalige/docblockr#318]
Hi, is it possible to remove the space before the ending `*/`?

Typing `/*` and then pressing `Enter` produces this output:
```
/*

 */
```
But what I really want is this:
```
/*

*/
```

Is there a Docblockr configuration that can change this behavior, or perhaps a setting in Atom itself? This is a bit of a nit-pick or personal preference, but it's been nagging at me for a while.

Thanks!

**Comment by MoritzKn** [comment]
Not sure if there is a configuration for it... if there is, it should be documented in the README. Closing this in an attempted to clean up the issue tracker.
