### ISSUE TITLE
0.4.2: Initial same-line auto-close `/**` with `*/`

### ISSUE THREAD

**Issue by lkraav** [nikhilkalige/docblockr#321]
Until you manually complete `/**` via enter/tab, remainder of the file gets commented out.

I'd prefer docblockr auto-close the initial comment on the same line, like `bracket-matcher` does for brackets, and avoid this flash of commented code on a large screen.

Is this possible already, or needs to be an implementation by something like docblockr?

**Comment by MoritzKn** [comment]
Hey, thanks for taking the time to write this up. Keep in mind this project is pretty much unmaintained and this wouldn't be in the scope of this package. Closing this in an attempted to clean up the issue tracker.
