### ISSUE TITLE
Usage together with compressor

### ISSUE THREAD

**Issue by Braintelligence** [nikhilkalige/docblockr#322]
Hi everyone! Excuse me if I missed such an option, but is there any way of getting

```
/*!
* My docblock
*/
```

Instead of 
```
/**
* My docblock
*/
```
?

Use-case is keeping comment blocks made this way even after minification by YUI compressor, for example with https://atom.io/packages/atom-minify

**Comment by MoritzKn** [comment]
Not sure if there is a configuration for it... if there is, it should be documented in the README. Closing this in an attempted to clean up the issue tracker.
