### ISSUE TITLE
Not generating type information for Typescript

### ISSUE THREAD

**Issue by chriszrc** [nikhilkalige/docblockr#324]
I'm on the latest version of Atom and docblockr (1.32.2, 0.13.7) and this is what I see:

![docblocker](https://user-images.githubusercontent.com/25695785/48674658-9b2f9a80-eb1c-11e8-8f72-a3561bd114ea.gif)

No matter what kind of function I try this on, I never get type information in the comment :(

**Comment by MoritzKn** [comment]
AFAIK this is intentional since in TypeScript the type information is already in the function signature duplicating it in the commented is not necessary.
