### ISSUE TITLE
请修复ATOM中不能使用逗号的问题

### ISSUE THREAD

**Issue by 233cy** [nikhilkalige/docblockr#330]
extra_tags中不能使用逗号

**Comment by 233cy** [comment]
@genbit

**Comment by 233cy** [comment]
@dmnd @UziTech @rosston

**Comment by UziTech** [comment]
Can you provide an example?

你能提供一个例子吗？

**Comment by 233cy** [comment]
![default](https://user-images.githubusercontent.com/29916783/51633994-fb641200-1f8d-11e9-8813-ebcfb416819d.png)
比如extra_tags我没办法在参数中加逗号，因为加入逗号就会直接换行。我这里只是演示，实际中我是要用于注解必须要用到逗号

**Comment by 233cy** [comment]
> 
> 
> ![default](https://user-images.githubusercontent.com/29916783/51633994-fb641200-1f8d-11e9-8813-ebcfb416819d.png)
> 比如extra_tags我没办法在参数中加逗号，因为加入逗号就会直接换行。我这里只是演示，实际中我是要用于注解必须要用到逗号

@UziTech

**Comment by UziTech** [comment]
I don't think this is an issue with docblockr.

It looks like it issue with the way that Atom gets an array setting.

I noticed you are using the full width comma `，(\u65292)` instead of `,(\u0026)` it looks like Atom doesn't split on that character.

**Comment by 233cy** [comment]
> 
> 
> I don't think this is an issue with docblockr.
> 
> It looks like it issue with the way that Atom gets an array setting.
> 
> 我注意到你的整个宽度上使用逗号`，(\uFF0C)`代替`,(\u002C)`它看起来并不像原子分裂性质。

我是要用,而不是，的。因为我要用于注解如：
![default](https://user-images.githubusercontent.com/29916783/51636986-885e9980-1f95-11e9-9107-bce42fec488b.png)

**Comment by 233cy** [comment]
![default](https://user-images.githubusercontent.com/29916783/51637169-fefb9700-1f95-11e9-8187-abca2d97d683.png)
比如这样，我不想让红色地方的逗号换行如何做

**Comment by UziTech** [comment]
I still think this is an issue with Atom not this package. Atom should interpret an escaped comma `\,` as a literal comma.

looks like you already opened a PR in https://github.com/atom/settings-view/pull/1101

**Comment by MoritzKn** [comment]
Closing this in an attempted to clean up the issue tracker and because I am not able to read Chinese and can not tell what this is about, sorry.
