### ISSUE TITLE
///, //!, and // not extending to new line

### ISSUE THREAD

**Issue by RaidoWolf** [nikhilkalige/docblockr#331]
Docblockr has been working great in the past when I've been using javadoc-style blocks, and it does correctly continue the comment on the next line when I type `/*` or `/**` and then hit enter. However, when I type `///`, `//!`, or `//` and then hit return, I get an empty new line. In the settings, "Extend double slash" is checked.

Maybe I'm just misunderstanding this plugin's functionality, but I've been looking into this for a few hours, and it seems like that's how it's supposed to work. If I'm wrong about that, I'd really appreciate being pointed in the right direction.

I'm running on Atom 1.34.0 (stable release channel) with docblockr 0.13.7. All settings for the plugin are currently set to their default values. I'm currently trying to use this feature in Rust files, but I've also tested JS and C++, and this problem is the same there as well. If there are any other details that could help, let me know and I'll get them to you ASAP.

Thanks for your time and awesome plugin!

**Comment by Osmose** [comment]
FWIW this previously worked for me but has stopped working. I don't think this is a misunderstanding of the feature.

**Comment by racineda** [comment]
Seeing the same behavior. Any update on this?

**Comment by MoritzKn** [comment]
This was probably fixed by #352 in version v0.14.0
