### ISSUE TITLE
Request of improvement: customised text width when wrapping comments

### ISSUE THREAD

**Issue by lacasta** [nikhilkalige/docblockr#336]
Very nice and useful package. Thanks !!  I was wondering if one could have a customised paragraph width that can supersede the one given by the rulers. Sometimes we might want the code line width be different (larger) than the comment line width

**Comment by MoritzKn** [comment]
Thanks! Not sure if there is a configuration for it... if there is, it should be documented in the README. Closing this in an attempted to clean up the issue tracker.
