### ISSUE TITLE
Suggestion: Add option to indent items with tabs instead of spaces

### ISSUE THREAD

**Issue by sbrl** [nikhilkalige/docblockr#339]
The first thing I do when I've finished filling out a docblock generated by this extension is replace all the spaces with tabs. It would be awesome if there was an option that I could change that would cause docblockr to generate them with the tabs in the first place.

**Comment by MoritzKn** [comment]
Not sure if there is a configuration for it... if there is, it should be documented in the README. Closing this in an attempted to clean up the issue tracker.

**Comment by sbrl** [comment]
Hrm, I don't think there's a configuration for this, @MoritzKn. Here's a specific example

With spaces:

```
/**
 * Duis sed arcu non tellus eleifend ullamcorper quis non erat. Curabitur
 *   metus elit, ultrices et tristique a, blandit at justo.
 * @param  {String} foo Lorem ipsum dolor sit amet.
 * @param  {Number} bar Nullam fringilla feugiat pretium. Quisque
 *   consectetur, risus eu pellentesque tincidunt, nulla ipsum imperdiet
 *   massa, sit amet adipiscing dolor.
 * @return {[Type]}
 */
```

With tabs: 
```
/**
 * Duis sed arcu non tellus eleifend ullamcorper quis non erat. Curabitur
 * metus elit, ultrices et tristique a, blandit at justo.
 * @param	{String}	foo		Lorem ipsum dolor sit amet.
 * @param	{Number}	bar		Nullam fringilla feugiat pretium. Quisque
 * @return	{[Type]}
 */
```

Since filing this issue, I have manually converted the generated spaces to tabs countless times. This would be an invaluable addition for me.
