### ISSUE TITLE
@constructor annotation in javascript class

### ISSUE THREAD

**Issue by janmarek** [nikhilkalige/docblockr#34]
When js function name starts with a upper case letter (is a class class constructor), annotation @constructor should be inserted. This can be optional.

``` js
/**
 * @constructor
 */
function Dog() {
    // ...
}
```

**Comment by MoritzKn** [comment]
+1

**Comment by MoritzKn** [comment]
I implemented it myself. 
See #176

**Comment by MoritzKn** [comment]
Finally fixed with #176
