### ISSUE TITLE
Rustdoc support doesn't seem to be working

### ISSUE THREAD

**Issue by jwir3** [nikhilkalige/docblockr#347]
**Steps to Reproduce**:
1. Install docblockr package v0.13.7 to atom.
2. Open a Rust file (verify that it's seen as a Rust file by checking the lower right corner)
3. Above an undocumented method, begin a documentation block by typing `///` and hitting return.

**Expected Results**:
  - :heavy_check_mark: Documentation block is continued on the next line by adding a `///` and indenting appropriately.

**Actual Results**:
  - :x: No comment or indentation prefixing is performed.

**Configuration**:

apm  2.1.7
npm  6.2.0
node 8.9.3 x64
atom 1.38.2

**Comment by MoritzKn** [comment]
This was probably fixed by #352 in version v0.14.0
