### ISSUE TITLE
Create docs without description [FeatureRequest]

### ISSUE THREAD

**Issue by iwasherefirst2** [nikhilkalige/docblockr#350]
Hey,  I think it would be awesome if one could disable the top comment `[foo description]` when creating a comment above a function.

![function-template](https://user-images.githubusercontent.com/1765602/79473392-59eb3500-8005-11ea-956c-d95314466ed3.gif)

Most of my function names are self-descriptive and do not require further docs, I still would love to add parameters and return type. I keep removing the line which makes 4-7 hits on the backslash key per doc block.

Would love that feature.

**Comment by MoritzKn** [comment]
Not sure if there is a configuration for it... if there is, it should be documented in the README if there isn't I am not inclined to add even more configs. Closing this in an attempted to clean up the issue tracker.
