### ISSUE TITLE
per-project Configuration file

### ISSUE THREAD

**Issue by amirhosseinhpv** [nikhilkalige/docblockr#353]
Hi, hope you are doing well.
First of all thank you for this awesome handy package for Atom.
I am requesting a feature to have separated configuration files per project, and package load its settings based on config file present in project root.
I need to have different extra_tags based on projects.

**Thank you so much for the time and effort**

**Comment by MoritzKn** [comment]
Maybe there is another atom package for project-specific configurations. I don't think this should be implemented in this package. Closing this in an attempted to clean up the issue tracker.
