### ISSUE TITLE
0.6.3 is semi-borked

### ISSUE THREAD

**Issue by Nxt3** [NikhilKalige/docblockr#56]
~~I'm on Atom v0.181.0 and I just updated docblockr to 0.6.2 and now nothing works. Tried restarting Atom, my computer--and even uninstalling and reinstalling the package.~~

0.6.3 has stuff working; however, functionality isn't the same as it was pre-0.6.2. See my comments below. Anything from javadoc'ing to just commenting seems to add an unnecessary newline.

**Comment by pesho** [comment]
0.6.2 is broken for me as well. Reverting to 0.5.8 helps.

**Comment by Nxt3** [comment]
0.6.3 fixes stuff, mostly.

If it type
`//TODO misc`
then insert a new line, instead of looking like this (pre-0.6.2):
`//TODO misc`
`//cursor here`

it looks like this:
`//TODO misc`
`//`
`//cursor here`

**Comment by AdamVig** [comment]
+1

**Comment by malko** [comment]
seems fixed now can you please confirm it's ok for you with latest version of docblocker

**Comment by AdamVig** [comment]
Adding a docblock (type `/**` then `enter`) on a JavaScript function still adds an unnecessary newline.

**Comment by NikhilKalige** [comment]
AdamVig Did you try with v0.7.2 ? Can you post an example?

```
/**
 * [asdf description]
 * @author nickf
 * @date        2015-05-23
 * @anotherdate 2015-05-23T21:33:40-070
 * @version     [version]
 * @param       {[type]}                xxxx [description]
 */
function asdf(xxxx) {
  // body...
}
```

This is what I get

**Comment by AdamVig** [comment]
@NikhilKalige I restarted Atom and it works fine now 😏My apologies. Great work on the patch!

**Comment by NikhilKalige** [comment]
Credits to @malko
