### ISSUE TITLE
simple_mode doesn't work

### ISSUE THREAD

**Issue by JonathanMEdwards** [nikhilkalige/docblockr#94]
As jsdoc templates are wrong in typescript (pending issue) I tried to turn off templates with simple_mode but it has no effect.

**Comment by MoritzKn** [comment]
I cant reproduce this..
Can you describe in details what "no effect" means?

**Comment by JonathanMEdwards** [comment]
"No effect" means that setting simple_mode to true has no effect - templates are still inserted. But this was a long time ago and I've switched to VS Code so I don't really care. Thanks.

**Comment by MoritzKn** [comment]
This was probably fixed long ago by #58
